/**
 * Canonical Library OS Excel/CSV columns — source of truth for import, export, and admin.
 * Matches Sheet2 of the editorial library workbook.
 * All columns are mandatory in the template header; cell values may be empty or "—".
 */
export const BULK_TEMPLATE_HEADERS = [
  'Title',
  'Subtitle',
  'Author',
  'Author Gender',
  'Country',
  'Original Language',
  'Translator',
  'Publication Year',
  'Pages',
  'ISBN',
  'Cover URL',
  'Fiction / Non-fiction',
  'Primary Genre',
  'Secondary Genre',
  'Subgenre',
  'Audience',
  'Series',
  'Series Name',
  'Series Number',
  'Standalone',
  'Themes',
  'Mood / Reading Experience',
  'Tropes',
  'Search Tags',
  'Female Author',
  'Female Protagonist',
  'Women Focus',
  'Collections',
  'Recommendation Occasion',
  'Reading Level',
  'Similar Books',
  'One-line Recommendation',
  'Short Description',
  'Instagram Hook',
  'Instagram Post Topic',
  'Best Posting Month',
  'Chapters.Aur.Chai Rating',
  'Read Status',
  'Date Read',
  'Format Read',
  'Owned',
  'Wishlist',
  'Awards',
  'Bestseller',
  'Adaptation',
  'BookTok Popular',
  'Bookstagram Popular',
] as const;

export type BulkTemplateHeader = (typeof BULK_TEMPLATE_HEADERS)[number];

/** Example row for the downloadable template (— = intentionally blank / N/A). */
export const BULK_TEMPLATE_EXAMPLE_ROW = [
  "On Earth We're Briefly Gorgeous",
  '—',
  'Ocean Vuong',
  'Male',
  'USA / Vietnam',
  'English',
  '—',
  '2019',
  '246',
  '—',
  '—',
  'Fiction',
  'Literary Fiction',
  'Contemporary Fiction',
  'Coming-of-Age',
  'Adult',
  'No',
  '—',
  '—',
  'Yes',
  'Identity; Family; Immigration; Love; Trauma',
  'Emotional; Reflective; Poetic; Intimate',
  'Coming of Age; Family Saga; Epistolary',
  'Literary Fiction; LGBTQ+; Vietnamese Diaspora; Identity; Family; Award-winning; Book Club; Emotional',
  'No',
  'No',
  'Secondary',
  'Literary Fiction; LGBTQ+ Literature',
  'Reflective Read; Book Club',
  'Advanced',
  'Shuggie Bain; Real Life; The Great Believers',
  'A lyrical novel exploring identity, family, memory, and the immigrant experience.',
  'Written as a letter from a son to his mother, this novel beautifully explores love, trauma, identity, and belonging through poetic prose.',
  "Some books don't tell a story—they leave a scar on your heart.",
  'Literary Fiction Everyone Should Read',
  'October',
  '',
  '',
  '',
  '',
  '',
  '',
  'Multiple Literary Awards',
  'Yes',
  'No',
  'Yes',
  'Yes',
] as const;
